name: playground
channels:
  - defaults
  - conda-forge
  - microsoft
dependencies:
  - python>=3.12
  - pip
  - gensim
  - numpy
  - pip:
    - requests
    - matplotlib
    - numpy
    - cython
    - POT
    - gensim
    - wordfreq